name: Ci/Cd Action

on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }} 
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Проверка изменений
        uses: actions/checkout@v2

      - name: установка Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Установка зависимостей
        run: pip install -r m2m-relations/requirements.txt

      - name: Линтер
        run: flake8 m2m-relations --exclude migration --ignore E501,F401,E302,W293,W391,W292


      - name: Тесты
        run: python m2m-relations/manage.py test
        env:
            SECRET_KEY: ${{ env.SECRET_KEY }}
            DEBUG: "0"
            ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
            DB_NAME: ${{ env.POSTGRES_DB }}
            DB_USER: ${{ env.POSTGRES_USER }}
            DB_PASSWORD: ${{ env.POSTGRES_PASS }}
            DB_HOST: ${{ env.POSTGRES_HOST }}
            DB_PORT: ${{ env.POSTGRES_PORT }}
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 80.78.243.180
          username: root
          password: oOp3gYr9DgAgY2zF
          script: |
            cd /home/mikl/'Рабочий стол'/dj-homeworks/2.2-databases-2/m2m-relations/
            git pull
            sudo systemctl restart gunicorn
      
